scalar Date
scalar ObjectId

type Todo {
  _id: String!
  title: String
  content: String!
  createdAt: Date
}

extend type Query {
  Todo(id: String!): Todo
  TodoList: [Todo]
}

extend type Mutation {
  addTodo(
    title: String
    content: String!
  ): Todo
  removeTodo(
    id: String!
  ): Todo
  updateTodo(
    id: String!
    title: String!
    content: String
  ): Todo
}

extend type Subscription {
  todoAdded: Todo
}